### ISSUE TITLE
Improve MacOS support

### ISSUE THREAD

**Issue by oddforms-design** [oddforms-design/Dongled#2]
- Looking to build the app as a MacOS catalyst app is on the to-do list since the app is almost fully compatible, mainly just need to rebuild the UI

**Comment by oddforms-design** [comment]
Setting more specific goals for this

**Comment by AndyHeyAdams** [comment]
Oh pleeeeeease!!! It would be awesome to use this app natively on mac and it would be the first easy-to-use available on the app store! If you need any help related to UI, I can help: I'm a designer, I own a design studio, and I love your app on iPad!
