### ISSUE TITLE
Capture appears rotated 180 degrees to true

### ISSUE THREAD

**Issue by HiRoS-neko** [oddforms-design/Dongled#6]
<img width="1163" alt="Screenshot 2024-08-07 at 11 08 29" src="https://github.com/user-attachments/assets/66a25866-a295-4dcd-91ad-264c701a965b">
Some way to customize this would be appreciated

**Comment by HiRoS-neko** [comment]
Only appears to be an issue on macos, works as intended with the correct rotation on ipad

**Comment by oddforms-design** [comment]
Thanks, a fix in place for next update.

**Comment by oddforms-design** [comment]
Fixed for v1.3.8 currently in testflight
